# Data

## Technical Description
# New York City Rat Sightings Dataset, collected from NYC Open Data. 
Data Source: https://data.cityofnewyork.us/Social-Services/Rat-Sightings/3q43-55fe
Data update frequency on the website: Everyday 9AM EST.
This dataset contains various columns representing different aspects of rat sightings in New York City from 2010 to present day and is updated daily on the Open Data Platform.

The data has 31 features with 232,536 rows. The description of the columns is as seen below:

1. **Unique Key**: A unique identifier for each sighting report.
2. **Created Date**: The date and time when the sighting report was created.
3. **Closed Date**: The date and time when the sighting report was resolved or closed.
4. **Agency**: The agency responsible for handling the sighting report.
5. **Agency Name**: The full name of the agency responsible for the report.
6. **Complaint Type**: The type of complaint or issue reported.
7. **Descriptor**: Additional details about the complaint.
8. **Location Type**: The type of location where the sighting occurred.
9. **Incident Zip**: The ZIP code where the sighting occurred.
10. **Incident Address**: The specific address of the sighting.
11. **Street Name**: The name of the street where the sighting occurred.
12. **Cross Street 1**: The first cross street near the sighting location.
13. **Cross Street 2**: The second cross street near the sighting location.
14. **Intersection Street 1**: One street at the nearest intersection.
15. **Intersection Street 2**: The other street at the nearest intersection.
16. **Address Type**: The type of address provided for the sighting.
17. **City**: The city where the sighting occurred.
18. **Landmark**: Any landmark near the sighting location.
19. **Facility Type**: The type of facility where the sighting occurred.
20. **Status**: The current status of the sighting report.
21. **Due Date**: The due date for resolving the report.
22. **Resolution Action Updated Date**: The last date when the resolution action was updated.
23. **Community Board**: The community board associated with the sighting location.
24. **Borough**: The borough in which the sighting occurred.
25. **X Coordinate (State Plane)**: The X coordinate of the sighting location in the State Plane Coordinate System.
26. **Y Coordinate (State Plane)**: The Y coordinate of the sighting location in the State Plane Coordinate System.
27. **Park Facility Name**: The name of the park facility near the sighting.
28. **Park Borough**: The borough of the park near the sighting.
29. **Latitude**: The latitude of the sighting location.
30. **Longitude**: The longitude of the sighting location.
31. **Location**: A textual representation of the sighting location, usually combining latitude and longitude.

## Research Plan:

Research Plan: New York City Rat Sightings Analysis

1\. Objective Definition

> Primary Objective:

i. Understand patterns and trends of rat sightings in New York City.

> Secondary Objectives:

i.  Identify rat sighting hotspots.

ii. Analyze response action effectiveness.

iii. Assess seasonal and yearly sighting trends.

Explore correlations with urban factors.

2\. Data Exploration

i. Data Cleaning: We will handle missing values, duplicates, and inconsistencies.

ii. Data Transformation: We will format the data correctly.

3\. Descriptive Analysis

i. Initial Overview: Summary statistics and basic visualizations.

ii. Geographical Analysis: Map-based distribution visualization.

iii. Temporal Analysis: Time-based trend analysis.

4\. In-Depth Analysis

i. Hotspot Identification: Clustering for area frequency analysis.

ii. Correlation Analysis: Examine relationships with other variables.

iii. Comparative Analysis: Frequency and response comparison across areas.

5\. Hypothesis Testing

> Test hypotheses based on initial findings, e.g., relation to population density, seasonal patterns.

6\. Predictive Modeling

> Develop and evaluate models for forecasting sightings based on existing data

7\. Actionable Insights and Recommendations

i. Derive insights for urban sanitation and pest control improvements.

ii. Policy recommendations to city authorities.

8\. Reporting

i. Visualizations: Detailed charts, graphs, and maps.

ii. Documentation: Comprehensive report on findings and methodology in the form of a book on Github.io

## Missing value analysis

This section analyses the missing values in the dataset.
```{r}
library(dplyr)
library(tidyr)

# reading dataset
data <- read.csv("https://data.cityofnewyork.us/resource/3q43-55fe.csv")
#data <- read.csv("C:\\Columbia\\EDAV\\Final Project\\Rat_Sightings.csv")

# Total number of rows in the dataset
total_rows <- nrow(data)

# Calculate missing values count and percentage for each column
missing_values <- data |> 
  summarise(across(everything(), ~sum(is.na(.)))) |>
  pivot_longer(cols = everything(), names_to = "Column", values_to = "count_missing") |>
  mutate(percentage_missing = round((count_missing / total_rows) * 100,2)) |>
  filter(count_missing > 0) # Filter out columns with no missing values

# Print the result
print(missing_values)
```

