# Introduction

As most residents know, there is a large and increasing rat population in New York City. In fact, it has been estimated that the rat population is now up to 3 million in 2023 (1). There has also been increasing discussion of the city’s rat problem in the media and by political figures. In April, Mayor Adams announced that there would now be a citywide director of rat mitigation (or “Rat Czar”) and appointed Kathleen Corradi to the position with the goal of reducing the city’s rat population (2). This announcement was also accompanied by a $3.5 million investment towards rat reduction work specifically in Harlem (2). As Corradi expressed, “Rats are a symptom of systemic issues, including sanitation, health, housing, and economic justice" (2).

Given this, it is clear that having a better understanding of NYC’s rat problem through data analysis and visualization is insightful and important to better understand inequities across the city. Additionally, with these new rat mitigation initiatives being implemented, having more information and insights about the current rat population will be useful to establish baseline trends. Those baseline trends could be re-evaluated and compared against in the future to better understand the effect of these rat migration initiatives. Finally, there are public health ramifications to NYC’s rat problem. A study conducted by Columbia University’s Mailman School of Public Health identified dangerous pathogens such as Salmonella, C.difficile, and E. coli on NYC rats (3). These pathogens can be left behind by rats by their saliva, urine, or feces, putting humans (and their pets) at risk of disease (3). The summary of the study also stresses that there is still much unknown about the public health risk of rats to humans and that monitoring of the rat population is needed to prevent dangerous public health situations like the rat-caused Black Death of the 1300s from occurring in the future (3). Clearly, identifying trends in NYC’s rat population through data analysis and visualization is incredibly useful from a public health standpoint. 

With the NYC Open Data Rat Sightings dataset, we will be able to address many questions about NYC’s rat population. Which parts of NYC is the rat population most and least prevalent, and how has that changed from 2010 to 2023? How do rat sightings differ between commercial, residential, and outdoor settings? Are rat sighting 311 requests more or less likely to be closed in certain neighborhoods or settings? How has the proportion or NYC rat sighting 311 requests that are closed changed over time?


Sources:

1. https://mandmpestcontrol.com/there-are-now-3-million-rats-in-new-york-city-study/

2. https://www.nyc.gov/office-of-the-mayor/news/249-23/mayor-adams-anoints-kathleen-corradi-nyc-s-first-ever-rat-czar-#/0 

3. https://www.publichealth.columbia.edu/news/rats-new-york-diseases-they-carry
